server:
  port: 8083
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: sso
              uri: http://keycloak:8100/
              predicates:
                - "Path=/api/sso/userinfo"
              filters:
                - RewritePath=/api/sso/userinfo, /auth/realms/local_realm/protocol/openid-connect/userinfo

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/auth/realms/local_realm
          jwk-set-uri: http://localhost:8100/auth/realms/local_realm/protocol/openid-connect/certs

adapter:
  einrichtungsverwaltung:
    base-url: http://localhost:8080
    security:
      token-url: https://ssodev.muenchen.de/auth/realms/A23/protocol/openid-connect/token
      client-id: traegerportal-eai
      client-secret: # add when running
      scope: lhm-core
      cache-seconds: 280
  webcomponents:
    base-url: http://localhost:8443

logging:
  include-application-group: false # disabled because application group is only relevant when deployed
  structured:
    format:
      console:
  level:
    root: INFO
    de.muenchen.refarch: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
